# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcu.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
import inspect
from dataclasses import dataclass
#general variables
@dataclass()
class gearO:
    state: str = ""
    O1: int = 0
    O2: int = 0
    O3: int = 0
    O4: int = 0

gear_list = "Park"
P=gearO(state="P")
R=gearO(state="R")
N=gearO(state="N")
G1=gearO(state="G1")
G2=gearO(state="G2")
G3=gearO(state="G3")
G4=gearO(state="G4")
G5=gearO(state="G5")
G6=gearO(state="G6")
G7=gearO(state="G7")
G8=gearO(state="G8")
G9=gearO(state="G9")
print(G1.O1)
# O1 = 0
# O2 = 0
# O3 = 0
# O4 = 0
class Ui_TCU(object):
    
    def setupUi(self, TCU):
        TCU.setObjectName("TCU")
        TCU.resize(807, 597)
        self.centralwidget = QtWidgets.QWidget(TCU)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Sensors = QtWidgets.QWidget()
        self.Sensors.setObjectName("Sensors")
        self.label = QtWidgets.QLabel(self.Sensors)
        self.label.setGeometry(QtCore.QRect(90, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Sensors)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.Sensors, "")
        self.Gearbox = QtWidgets.QWidget()
        self.Gearbox.setObjectName("Gearbox")
        self.set = QtWidgets.QPushButton(self.Gearbox)
        self.set.setGeometry(QtCore.QRect(670, 410, 75, 23))
        self.set.setObjectName("set")
        # Gear Box List 
        self.gear_list = QtWidgets.QListWidget(self.Gearbox)
        self.gear_list.setGeometry(QtCore.QRect(10, 10, 71, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gear_list.setFont(font)
        self.gear_list.setObjectName("gear_list")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        # self.gear_list.currentItemChanged.connect(self.index_changed)
        self.gear_list.currentTextChanged.connect(self.text_changed)
#########################################################################
        # table 
        self.down_shift_table = QtWidgets.QTableWidget(self.Gearbox)
        self.down_shift_table.setGeometry(QtCore.QRect(470, 310, 311, 91))
        self.down_shift_table.setFrameShape(QtWidgets.QFrame.Box)
        self.down_shift_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.down_shift_table.setMidLineWidth(1)
        self.down_shift_table.setObjectName("down_shift_table")
        self.down_shift_table.setColumnCount(5)
        self.down_shift_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setItem(0, 0, item)
        self.down_shift_table.horizontalHeader().setCascadingSectionResizes(False)
        self.down_shift_table.horizontalHeader().setDefaultSectionSize(50)
        self.up_shift_table = QtWidgets.QTableWidget(self.Gearbox)
        self.up_shift_table.setGeometry(QtCore.QRect(160, 310, 311, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_shift_table.sizePolicy().hasHeightForWidth())
        self.up_shift_table.setSizePolicy(sizePolicy)
        self.up_shift_table.setFrameShape(QtWidgets.QFrame.Box)
        self.up_shift_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.up_shift_table.setMidLineWidth(1)
        self.up_shift_table.setObjectName("up_shift_table")
        self.up_shift_table.setColumnCount(5)
        self.up_shift_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setItem(0, 0, item)
        self.up_shift_table.horizontalHeader().setCascadingSectionResizes(False)
        self.up_shift_table.horizontalHeader().setDefaultSectionSize(50)
        self.up_shift_table.horizontalHeader().setMinimumSectionSize(30)
        ###########################################################
        self.reset = QtWidgets.QPushButton(self.Gearbox)
        self.reset.setGeometry(QtCore.QRect(590, 410, 75, 23))
        self.reset.setObjectName("reset")
        self.read = QtWidgets.QPushButton(self.Gearbox)
        self.read.setGeometry(QtCore.QRect(510, 410, 75, 23))
        self.read.setObjectName("read")
        self.label_3 = QtWidgets.QLabel(self.Gearbox)
        self.label_3.setGeometry(QtCore.QRect(290, 290, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Gearbox)
        self.label_4.setGeometry(QtCore.QRect(590, 290, 51, 20))
        self.label_4.setObjectName("label_4")
        self.splitter = QtWidgets.QSplitter(self.Gearbox)
        self.splitter.setGeometry(QtCore.QRect(90, 10, 81, 311))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        ###################################################
        self.checkBox_1 = QtWidgets.QCheckBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_1.sizePolicy().hasHeightForWidth())
        self.checkBox_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setTristate(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_1.stateChanged.connect(lambda: self.show_state(self.checkBox_1.checkState(),1))

        self.checkBox_2 = QtWidgets.QCheckBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setTristate(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.stateChanged.connect(lambda: self.show_state(self.checkBox_2.checkState(),2))
        self.checkBox_3 = QtWidgets.QCheckBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setTristate(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.stateChanged.connect(lambda: self.show_state(self.checkBox_3.checkState(),3))
        self.checkBox_4 = QtWidgets.QCheckBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setTristate(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_4.stateChanged.connect(lambda: self.show_state(self.checkBox_4.checkState(),4))
        
        self.tabWidget.addTab(self.Gearbox, "")
        self.TCC = QtWidgets.QWidget()
        self.TCC.setObjectName("TCC")
        self.tabWidget.addTab(self.TCC, "")
        self.PCS = QtWidgets.QWidget()
        self.PCS.setObjectName("PCS")
        self.tabWidget.addTab(self.PCS, "")
        self.SL = QtWidgets.QWidget()
        self.SL.setObjectName("SL")
        self.tabWidget.addTab(self.SL, "")
        TCU.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TCU)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        TCU.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TCU)
        self.statusbar.setObjectName("statusbar")
        TCU.setStatusBar(self.statusbar)

        self.retranslateUi(TCU)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TCU)

    def retranslateUi(self, TCU):
        _translate = QtCore.QCoreApplication.translate
        TCU.setWindowTitle(_translate("TCU", "Transmission control unit"))
        self.label.setText(_translate("TCU", "Selector"))
        self.label_2.setText(_translate("TCU", "Selector:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sensors), _translate("TCU", "Sensors"))
        self.set.setText(_translate("TCU", "Set"))
        __sortingEnabled = self.gear_list.isSortingEnabled()
        self.gear_list.setSortingEnabled(False)
        item = self.gear_list.item(0)
        item.setText(_translate("TCU", "Park"))
        item = self.gear_list.item(1)
        item.setText(_translate("TCU", "Reverse"))
        item = self.gear_list.item(2)
        item.setText(_translate("TCU", "Neutral"))
        item = self.gear_list.item(3)
        item.setText(_translate("TCU", "Gear 1"))
        item = self.gear_list.item(4)
        item.setText(_translate("TCU", "Gear 2"))
        item = self.gear_list.item(5)
        item.setText(_translate("TCU", "Gear 3"))
        item = self.gear_list.item(6)
        item.setText(_translate("TCU", "Gear 4"))
        item = self.gear_list.item(7)
        item.setText(_translate("TCU", "Gear 5"))
        item = self.gear_list.item(8)
        item.setText(_translate("TCU", "Gear 6"))
        item = self.gear_list.item(9)
        item.setText(_translate("TCU", "Gear 7"))
        item = self.gear_list.item(10)
        item.setText(_translate("TCU", "Gear 8"))
        item = self.gear_list.item(11)
        item.setText(_translate("TCU", "Gear 9"))
        self.gear_list.setSortingEnabled(__sortingEnabled)
        item = self.down_shift_table.verticalHeaderItem(0)
        item.setText(_translate("TCU", "Speed"))
        item = self.down_shift_table.verticalHeaderItem(1)
        item.setText(_translate("TCU", "Throttle"))
        item = self.down_shift_table.horizontalHeaderItem(0)
        item.setText(_translate("TCU", "1"))
        item = self.down_shift_table.horizontalHeaderItem(1)
        item.setText(_translate("TCU", "2"))
        item = self.down_shift_table.horizontalHeaderItem(2)
        item.setText(_translate("TCU", "3"))
        item = self.down_shift_table.horizontalHeaderItem(3)
        item.setText(_translate("TCU", "4"))
        item = self.down_shift_table.horizontalHeaderItem(4)
        item.setText(_translate("TCU", "5"))
        __sortingEnabled = self.down_shift_table.isSortingEnabled()
        self.down_shift_table.setSortingEnabled(False)
        self.down_shift_table.setSortingEnabled(__sortingEnabled)
        item = self.up_shift_table.verticalHeaderItem(0)
        item.setText(_translate("TCU", "Speed"))
        item = self.up_shift_table.verticalHeaderItem(1)
        item.setText(_translate("TCU", "Throttle"))
        item = self.up_shift_table.horizontalHeaderItem(0)
        item.setText(_translate("TCU", "1"))
        item = self.up_shift_table.horizontalHeaderItem(1)
        item.setText(_translate("TCU", "2"))
        item = self.up_shift_table.horizontalHeaderItem(2)
        item.setText(_translate("TCU", "3"))
        item = self.up_shift_table.horizontalHeaderItem(3)
        item.setText(_translate("TCU", "4"))
        item = self.up_shift_table.horizontalHeaderItem(4)
        item.setText(_translate("TCU", "5"))
        __sortingEnabled = self.up_shift_table.isSortingEnabled()
        self.up_shift_table.setSortingEnabled(False)
        self.up_shift_table.setSortingEnabled(__sortingEnabled)
        self.reset.setText(_translate("TCU", "Reset"))
        self.read.setText(_translate("TCU", "Read"))
        self.label_3.setText(_translate("TCU", "Up Shift"))
        self.label_4.setText(_translate("TCU", "Down Shift"))
        self.checkBox_1.setText(_translate("TCU", "Out 1"))
        self.checkBox_2.setText(_translate("TCU", "Out 2"))
        self.checkBox_3.setText(_translate("TCU", "Out 3"))
        self.checkBox_4.setText(_translate("TCU", "Out 4"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gearbox), _translate("TCU", "Shift solenoids"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TCC), _translate("TCU", "Torque converter clutch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PCS), _translate("TCU", "Pressure control solenoids"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SL), _translate("TCU", "Shift Lock"))
    
    # def index_changed(self, i): # Not an index, i is a QListWidgetItem
    #     print(i.text())

    def text_changed(self, s): # s is a str
        global gear_list
        global G1 , G2 , G3 , G4 , G5 , G6 , G7 , G8 , G9
        global P , R , N
        gear_list=s
        print(s)
        if gear_list=="Park" :
            self.checkBox_1.setCheckState(P.O1)
            self.checkBox_2.setCheckState(P.O2)
            self.checkBox_3.setCheckState(P.O3)
            self.checkBox_4.setCheckState(P.O4)
        if gear_list=="Reverse" :
            self.checkBox_1.setCheckState(R.O1)
            self.checkBox_2.setCheckState(R.O2)
            self.checkBox_3.setCheckState(R.O3)
            self.checkBox_4.setCheckState(R.O4)
        if gear_list=="Neutral" :
            
            self.checkBox_1.setCheckState(N.O1)
            self.checkBox_2.setCheckState(N.O2)
            self.checkBox_3.setCheckState(N.O3)
            self.checkBox_4.setCheckState(N.O4)
        if gear_list=="Gear 1" :
            
            self.checkBox_1.setCheckState(G1.O1)
            self.checkBox_2.setCheckState(G1.O2)
            self.checkBox_3.setCheckState(G1.O3)
            self.checkBox_4.setCheckState(G1.O4)
        if gear_list=="Gear 2" :
            
            self.checkBox_1.setCheckState(G2.O1)
            self.checkBox_2.setCheckState(G2.O2)
            self.checkBox_3.setCheckState(G2.O3)
            self.checkBox_4.setCheckState(G2.O4)
        if gear_list=="Gear 3" :
            
            self.checkBox_1.setCheckState(G3.O1)
            self.checkBox_2.setCheckState(G3.O2)
            self.checkBox_3.setCheckState(G3.O3)
            self.checkBox_4.setCheckState(G3.O4)
        if gear_list=="Gear 4" :
            
            self.checkBox_1.setCheckState(G4.O1)
            self.checkBox_2.setCheckState(G4.O2)
            self.checkBox_3.setCheckState(G4.O3)
            self.checkBox_4.setCheckState(G4.O4)
        if gear_list=="Gear 5" :
            self.checkBox_1.setCheckState(G5.O1)
            self.checkBox_2.setCheckState(G5.O2)
            self.checkBox_3.setCheckState(G5.O3)
            self.checkBox_4.setCheckState(G5.O4)
        if gear_list=="Gear 6" :
            self.checkBox_1.setCheckState(G6.O1)
            self.checkBox_2.setCheckState(G6.O2)
            self.checkBox_3.setCheckState(G6.O3)
            self.checkBox_4.setCheckState(G6.O4)
        if gear_list=="Gear 7" :
            
            self.checkBox_1.setCheckState(G7.O1)
            self.checkBox_2.setCheckState(G7.O2)
            self.checkBox_3.setCheckState(G7.O3)
            self.checkBox_4.setCheckState(G7.O4)
        if gear_list=="Gear 8" :
            self.checkBox_1.setCheckState(G8.O1)
            self.checkBox_2.setCheckState(G8.O2)
            self.checkBox_3.setCheckState(G8.O3)
            self.checkBox_4.setCheckState(G8.O4)
        if gear_list=="Gear 9" :
            self.checkBox_1.setCheckState(G9.O1)
            self.checkBox_2.setCheckState(G9.O2)
            self.checkBox_3.setCheckState(G9.O3)
            self.checkBox_4.setCheckState(G9.O4)
        
        
    def show_state(self,sig,num):
        global gear_list
        global G1 , G2 , G3 , G4 , G5 , G6 , G7 , G8 , G9
        global P , R , N
        if gear_list=="Park" :
            
            if num == 1 :
                P.O1=sig
            if num == 2 :
                P.O2=sig
            if num == 3 :
                P.O3=sig
            if num == 4 :
                P.O4=sig
            print(P)
        if gear_list=="Reverse" :
            
            if num == 1 :
                R.O1=sig
            if num == 2 :
                R.O2=sig
            if num == 3 :
                R.O3=sig
            if num == 4 :
                R.O4=sig
            print(R)
        if gear_list=="Neutral" :
            
            if num == 1 :
                N.O1=sig
            if num == 2 :
                N.O2=sig
            if num == 3 :
                N.O3=sig
            if num == 4 :
                N.O4=sig
            print(N)
        if gear_list=="Gear 1" :
            
            if num == 1 :
                G1.O1=sig
            if num == 2 :
                G1.O2=sig
            if num == 3 :
                G1.O3=sig
            if num == 4 :
                G1.O4=sig
        if gear_list=="Gear 2" :
            
            if num == 1 :
                G2.O1=sig
            if num == 2 :
                G2.O2=sig
            if num == 3 :
                G2.O3=sig
            if num == 4 :
                G2.O4=sig
        if gear_list=="Gear 3" :
            
            if num == 1 :
                G3.O1=sig
            if num == 2 :
                G3.O2=sig
            if num == 3 :
                G3.O3=sig
            if num == 4 :
                G3.O4=sig
        if gear_list=="Gear 4" :
            
            if num == 1 :
                G4.O1=sig
            if num == 2 :
                G4.O2=sig
            if num == 3 :
                G4.O3=sig
            if num == 4 :
                G4.O4=sig
        if gear_list=="Gear 5" :
            if num == 1 :
                G5.O1=sig
            if num == 2 :
                G5.O2=sig
            if num == 3 :
                G5.O3=sig
            if num == 4 :
                G5.O4=sig
        if gear_list=="Gear 6" :
            
            if num == 1 :
                G6.O1=sig
            if num == 2 :
                G6.O2=sig
            if num == 3 :
                G6.O3=sig
            if num == 4 :
                G6.O4=sig
        if gear_list=="Gear 7" :
            
            if num == 1 :
                G7.O1=sig
            if num == 2 :
                G7.O2=sig
            if num == 3 :
                G7.O3=sig
            if num == 4 :
                G7.O4=sig
        if gear_list=="Gear 8" :
            
            if num == 1 :
                G8.O1=sig
            if num == 2 :
                G8.O2=sig
            if num == 3 :
                G8.O3=sig
            if num == 4 :
                G8.O4=sig
        if gear_list=="Gear 9" :
            
            if num == 1 :
                G9.O1=sig
            if num == 2 :
                G9.O2=sig
            if num == 3 :
                G9.O3=sig
            if num == 4 :
                G9.O4=sig
            

        # print(P)
        
        print(gear_list)
        # print(s)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TCU = QtWidgets.QMainWindow()
    ui = Ui_TCU()
    ui.setupUi(TCU)
    TCU.show()
    sys.exit(app.exec_())
