# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcu.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets  
from PyQt5.QtCore import *
from PyQt5.QtChart import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QDialog, QApplication, QPushButton, QVBoxLayout , QStackedLayout  
from PyQt5.QtQuick import QQuickView
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt 
from mpl_toolkits import mplot3d
import random
import numpy as np
from dataclasses import dataclass, field
from matplotlib import cm
from matplotlib.ticker import LinearLocator

#general variables
@dataclass()
class gearO:
    state: str = ""
    O1: int = 0
    O2: int = 0
    O3: int = 0
    O4: int = 0
    O5: int = 0
@dataclass()
class gearP:
    state: str = ""
    data_x: list[int] = field(default_factory=list)
    data_y: list[int] = field(default_factory=list) 
    ratio: float = 1.0
    O1: int = 0
    O2: int = 0
    O3: int = 0
    O4: int = 0
    O5: int = 0
# [20,40,60,80,100 ]  [[1,1],[40,20],[80,40],[120,90],[200,100]]
gear_list = "Park"
# P=gearO(state="P")
# R=gearO(state="R")
# N=gearO(state="N")
# G1=gearO(state="G1")
# G2=gearO(state="G2")
# G3=gearO(state="G3")
# G4=gearO(state="G4")
# G5=gearO(state="G5")
# G6=gearO(state="G6")
# G7=gearO(state="G7")
# G8=gearO(state="G8")
# G9=gearO(state="G9")

P=gearP(state="P")
R=gearP(state="R")
N=gearP(state="N")
G1=gearP(state="G1",data_x=[20,40,60,80,100 ],data_y=[[1,0],[40,0],[80,0],[120,0],[200,0]])
G2=gearP(state="G2",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])
G3=gearP(state="G3",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])
G4=gearP(state="G4",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])
G5=gearP(state="G5",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])
G6=gearP(state="G6",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])
G7=gearP(state="G7",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])
G8=gearP(state="G8",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])
G9=gearP(state="G9",data_x=[20,40,60,80,100 ],data_y=[[1,1],[40,20],[80,40],[120,90],[200,100]])

show = 0

## sensor read ###
Engine_speed = 3200
TPS_V = 53
Speed = 75
Fluid_temp = 85
line_press = 70
TCU_temp = 25
TCU_volt = 12
TCU_amp = 1.0
O1AMP = 1.1
O2AMP = 1.2
O3AMP = 1.3 
O4AMP = 1.4
O5AMP = 1.5
O6AMP = 1.6
O7AMP = 1.7
O8AMP = 1.8
Drive_mod = "N" # N : normal // S: Sport // E: Economy // 
Brake_sig = 0
Ign_sig = 0 

# O1 = 0
# O2 = 0
# O3 = 0
# O4 = 0
class Ui_TCU(object):
    
    def setupUi(self, TCU):
        # super(Ui_TCU, self).__init__(TCU)
        global show
        TCU.setObjectName("TCU")
        TCU.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(TCU)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Sensors = QtWidgets.QWidget()
        self.Sensors.setObjectName("Sensors")
        
        self.RPMgaugeView = QQuickView()
        self.RPMcontain = QtWidgets.QWidget.createWindowContainer(self.RPMgaugeView, self.Sensors)
        self.RPMcontain.setGeometry(QtCore.QRect(50, 50, 250, 250))
        self.RPMcontain.setAutoFillBackground(False)
        # self.RPMcontain.setStyleSheet("color: #191919 ; background-color: yellow")
        self.RPMgaugeView.lower
        self.RPMcontain.lower
        self.RPMgaugeView.setSource(QUrl('RPM.qml'))
        self.RPMGauge=self.RPMgaugeView.findChild(QObject,'rpm_gauge')
        self.RPMGauge.setProperty('rpm_value',8300)

        self.TPSgaugeView = QQuickView()
        self.TPScontain = QtWidgets.QWidget.createWindowContainer(self.TPSgaugeView, self.Sensors)
        self.TPScontain.setGeometry(QtCore.QRect(350, 50, 250, 250))
        self.TPSgaugeView.setSource(QUrl('TPS.qml'))
        self.TPSGauge=self.TPSgaugeView.findChild(QObject,'tps_gauge')
        self.TPSGauge.setProperty('tps_value',72)
        self.tabWidget.addTab(self.Sensors, "")

        self.TFTgaugeView = QQuickView()
        self.TFTcontain = QtWidgets.QWidget.createWindowContainer(self.TFTgaugeView, self.Sensors)
        self.TFTcontain.setGeometry(QtCore.QRect(50, 350, 250, 250))
        self.TFTgaugeView.setSource(QUrl('TFT.qml'))
        self.TFTGauge=self.TFTgaugeView.findChild(QObject,'tft_gauge')
        self.TFTGauge.setProperty('tft_value',55)

        self.SPEEDgaugeView = QQuickView()
        self.SPEEDcontain = QtWidgets.QWidget.createWindowContainer(self.SPEEDgaugeView, self.Sensors)
        self.SPEEDcontain.setGeometry(QtCore.QRect(650, 50, 250, 250))
        self.SPEEDgaugeView.setSource(QUrl('SPEED.qml'))
        self.SPEEDGauge=self.SPEEDgaugeView.findChild(QObject,'speed_gauge')
        self.SPEEDGauge.setProperty('speed_value',55)

        self.LPgaugeView = QQuickView()
        self.LPcontain = QtWidgets.QWidget.createWindowContainer(self.LPgaugeView, self.Sensors)
        self.LPcontain.setGeometry(QtCore.QRect(350, 350, 250, 250))
        self.LPgaugeView.setSource(QUrl('LP.qml'))
        self.LPGauge=self.LPgaugeView.findChild(QObject,'lp_gauge')
        self.LPGauge.setProperty('lp_value',72)
        #### TCU Health box ###################
        self.health_F = QtWidgets.QFrame(self.Sensors)
        self.health_F.setGeometry(QtCore.QRect(650, 380, 281, 191))
        self.health_F.setAutoFillBackground(False)
        self.health_F.setFrameShape(QtWidgets.QFrame.Box)
        self.health_F.setFrameShadow(QtWidgets.QFrame.Raised)
        self.health_F.setObjectName("health_F")
        self.health_F.setStyleSheet('background-color:#2ecc71')
        self.tcu_tmp_l = QtWidgets.QLabel(self.health_F)
        self.tcu_tmp_l.setGeometry(QtCore.QRect(0, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tcu_tmp_l.setFont(font)
        self.tcu_tmp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.tcu_tmp_l.setObjectName("tcu_tmp_l")
        self.tcu_tmp_v = QtWidgets.QLCDNumber(self.health_F)
        self.tcu_tmp_v.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tcu_tmp_v.setFont(font)
        self.tcu_tmp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.tcu_tmp_v.setLineWidth(1)
        self.tcu_tmp_v.setSmallDecimalPoint(True)
        self.tcu_tmp_v.setDigitCount(3)
        self.tcu_tmp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.tcu_tmp_v.setProperty("intValue", 2)
        self.tcu_tmp_v.setObjectName("tcu_tmp_v")
        self.tcu_volt_l = QtWidgets.QLabel(self.health_F)
        self.tcu_volt_l.setGeometry(QtCore.QRect(140, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tcu_volt_l.setFont(font)
        self.tcu_volt_l.setAlignment(QtCore.Qt.AlignCenter)
        self.tcu_volt_l.setObjectName("tcu_volt_l")
        self.tcu_volt_v = QtWidgets.QLCDNumber(self.health_F)
        self.tcu_volt_v.setGeometry(QtCore.QRect(220, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tcu_volt_v.setFont(font)
        self.tcu_volt_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.tcu_volt_v.setLineWidth(1)
        self.tcu_volt_v.setSmallDecimalPoint(True)
        self.tcu_volt_v.setDigitCount(3)
        self.tcu_volt_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.tcu_volt_v.setProperty("intValue", 2)
        self.tcu_volt_v.setObjectName("tcu_volt_v")
        self.tcu_ampl = QtWidgets.QLabel(self.health_F)
        self.tcu_ampl.setGeometry(QtCore.QRect(0, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tcu_ampl.setFont(font)
        self.tcu_ampl.setAlignment(QtCore.Qt.AlignCenter)
        self.tcu_ampl.setObjectName("tcu_ampl")
        self.tcu_amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.tcu_amp_v.setGeometry(QtCore.QRect(80, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tcu_amp_v.setFont(font)
        self.tcu_amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.tcu_amp_v.setLineWidth(1)
        self.tcu_amp_v.setSmallDecimalPoint(True)
        self.tcu_amp_v.setDigitCount(3)
        self.tcu_amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.tcu_amp_v.setProperty("intValue", 2)
        self.tcu_amp_v.setObjectName("tcu_amp_v")
        self.label_6 = QtWidgets.QLabel(self.health_F)
        self.label_6.setGeometry(QtCore.QRect(140, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.health_F)
        self.lcdNumber_4.setGeometry(QtCore.QRect(220, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_4.setLineWidth(1)
        self.lcdNumber_4.setSmallDecimalPoint(True)
        self.lcdNumber_4.setDigitCount(3)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_4.setProperty("intValue", 2)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.o2amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o2amp_v.setGeometry(QtCore.QRect(220, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o2amp_v.setFont(font)
        self.o2amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o2amp_v.setLineWidth(1)
        self.o2amp_v.setSmallDecimalPoint(True)
        self.o2amp_v.setDigitCount(3)
        self.o2amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o2amp_v.setProperty("intValue", 2)
        self.o2amp_v.setObjectName("o2amp_v")
        self.o2amp_l = QtWidgets.QLabel(self.health_F)
        self.o2amp_l.setGeometry(QtCore.QRect(140, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o2amp_l.setFont(font)
        self.o2amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o2amp_l.setObjectName("o2amp_l")
        self.o1amp_l = QtWidgets.QLabel(self.health_F)
        self.o1amp_l.setGeometry(QtCore.QRect(0, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o1amp_l.setFont(font)
        self.o1amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o1amp_l.setObjectName("o1amp_l")
        self.o1amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o1amp_v.setGeometry(QtCore.QRect(80, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o1amp_v.setFont(font)
        self.o1amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o1amp_v.setLineWidth(1)
        self.o1amp_v.setSmallDecimalPoint(True)
        self.o1amp_v.setDigitCount(3)
        self.o1amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o1amp_v.setProperty("intValue", 2)
        self.o1amp_v.setObjectName("o1amp_v")
        self.o3amp_l = QtWidgets.QLabel(self.health_F)
        self.o3amp_l.setGeometry(QtCore.QRect(0, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o3amp_l.setFont(font)
        self.o3amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o3amp_l.setObjectName("o3amp_l")
        self.o4amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o4amp_v.setGeometry(QtCore.QRect(220, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o4amp_v.setFont(font)
        self.o4amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o4amp_v.setLineWidth(1)
        self.o4amp_v.setSmallDecimalPoint(True)
        self.o4amp_v.setDigitCount(3)
        self.o4amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o4amp_v.setProperty("intValue", 2)
        self.o4amp_v.setObjectName("o4amp_v")
        self.o3amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o3amp_v.setGeometry(QtCore.QRect(80, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o3amp_v.setFont(font)
        self.o3amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o3amp_v.setLineWidth(1)
        self.o3amp_v.setSmallDecimalPoint(True)
        self.o3amp_v.setDigitCount(3)
        self.o3amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o3amp_v.setProperty("intValue", 2)
        self.o3amp_v.setObjectName("o3amp_v")
        self.o4amp_l = QtWidgets.QLabel(self.health_F)
        self.o4amp_l.setGeometry(QtCore.QRect(140, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o4amp_l.setFont(font)
        self.o4amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o4amp_l.setObjectName("o4amp_l")
        self.o6amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o6amp_v.setGeometry(QtCore.QRect(220, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o6amp_v.setFont(font)
        self.o6amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o6amp_v.setLineWidth(1)
        self.o6amp_v.setSmallDecimalPoint(True)
        self.o6amp_v.setDigitCount(3)
        self.o6amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o6amp_v.setProperty("intValue", 2)
        self.o6amp_v.setObjectName("o6amp_v")
        self.o5amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o5amp_v.setGeometry(QtCore.QRect(80, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o5amp_v.setFont(font)
        self.o5amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o5amp_v.setLineWidth(1)
        self.o5amp_v.setSmallDecimalPoint(True)
        self.o5amp_v.setDigitCount(3)
        self.o5amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o5amp_v.setProperty("intValue", 2)
        self.o5amp_v.setObjectName("o5amp_v")
        self.o5amp_l = QtWidgets.QLabel(self.health_F)
        self.o5amp_l.setGeometry(QtCore.QRect(0, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o5amp_l.setFont(font)
        self.o5amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o5amp_l.setObjectName("o5amp_l")
        self.o6amp_l = QtWidgets.QLabel(self.health_F)
        self.o6amp_l.setGeometry(QtCore.QRect(140, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o6amp_l.setFont(font)
        self.o6amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o6amp_l.setObjectName("o6amp_l")
        self.o7amp_l = QtWidgets.QLabel(self.health_F)
        self.o7amp_l.setGeometry(QtCore.QRect(0, 160, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o7amp_l.setFont(font)
        self.o7amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o7amp_l.setObjectName("o7amp_l")
        self.o8amp_l = QtWidgets.QLabel(self.health_F)
        self.o8amp_l.setGeometry(QtCore.QRect(140, 160, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.o8amp_l.setFont(font)
        self.o8amp_l.setAlignment(QtCore.Qt.AlignCenter)
        self.o8amp_l.setObjectName("o8amp_l")
        self.o8amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o8amp_v.setGeometry(QtCore.QRect(220, 160, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o8amp_v.setFont(font)
        self.o8amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o8amp_v.setLineWidth(1)
        self.o8amp_v.setSmallDecimalPoint(True)
        self.o8amp_v.setDigitCount(3)
        self.o8amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o8amp_v.setProperty("intValue", 2)
        self.o8amp_v.setObjectName("o8amp_v")
        self.o7amp_v = QtWidgets.QLCDNumber(self.health_F)
        self.o7amp_v.setGeometry(QtCore.QRect(80, 160, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.o7amp_v.setFont(font)
        self.o7amp_v.setFrameShape(QtWidgets.QFrame.Panel)
        self.o7amp_v.setLineWidth(1)
        self.o7amp_v.setSmallDecimalPoint(True)
        self.o7amp_v.setDigitCount(3)
        self.o7amp_v.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.o7amp_v.setProperty("intValue", 2)
        self.o7amp_v.setObjectName("o7amp_v")
        self.health_L = QtWidgets.QLabel(self.Sensors)
        self.health_L.setGeometry(QtCore.QRect(720, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.health_L.setFont(font)
        self.health_L.setFrameShape(QtWidgets.QFrame.Panel)
        self.health_L.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.health_L.setAlignment(QtCore.Qt.AlignCenter)
        self.health_L.setObjectName("health_L")
        self.health_L.setStyleSheet('background-color: #17a589')
        #### status #########################################
        self.status = QtWidgets.QFrame(self.Sensors)
        self.status.setGeometry(QtCore.QRect(130, 620, 701, 43))
        self.status.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status.setObjectName("status")
        self.status.setStyleSheet('background-color: #2e86c1')
        self.dmod_l = QtWidgets.QLabel(self.status)
        self.dmod_l.setGeometry(QtCore.QRect(200, 0, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dmod_l.setFont(font)
        self.dmod_l.setAlignment(QtCore.Qt.AlignCenter)
        self.dmod_l.setObjectName("dmod_l")
        self.dmod_v = QtWidgets.QLabel(self.status)
        self.dmod_v.setGeometry(QtCore.QRect(290, 1, 71, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dmod_v.setFont(font)
        self.dmod_v.setAlignment(QtCore.Qt.AlignCenter)
        self.dmod_v.setObjectName("dmod_v")
        self.gear_v = QtWidgets.QLabel(self.status)
        self.gear_v.setGeometry(QtCore.QRect(450, 1, 41, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gear_v.setFont(font)
        self.gear_v.setAlignment(QtCore.Qt.AlignCenter)
        self.gear_v.setObjectName("gear_v")
        self.gear_l = QtWidgets.QLabel(self.status)
        self.gear_l.setGeometry(QtCore.QRect(380, 1, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gear_l.setFont(font)
        self.gear_l.setAlignment(QtCore.Qt.AlignCenter)
        self.gear_l.setObjectName("gear_l")
        self.brake_l = QtWidgets.QLabel(self.status)
        self.brake_l.setGeometry(QtCore.QRect(510, 1, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.brake_l.setFont(font)
        self.brake_l.setAlignment(QtCore.Qt.AlignCenter)
        self.brake_l.setObjectName("brake_l")
        self.brake_l.setStyleSheet('background-color: #FFBF00')
        self.ing_l = QtWidgets.QLabel(self.status)
        self.ing_l.setGeometry(QtCore.QRect(600, 1, 91, 40))
        self.ing_l.setStyleSheet('background-color: #DE3163')
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ing_l.setFont(font)
        self.ing_l.setAlignment(QtCore.Qt.AlignCenter)
        self.ing_l.setObjectName("ing_l")
        self.status_v = QtWidgets.QLabel(self.status)
        self.status_v.setGeometry(QtCore.QRect(70, 1, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status_v.setFont(font)
        self.status_v.setAlignment(QtCore.Qt.AlignCenter)
        self.status_v.setObjectName("status_v")
        self.status_v.setStyleSheet('background-color:  #DE3163')
        # self.status_v.setStyleSheet('background-color:  #17a589')
        self.status_l = QtWidgets.QLabel(self.status)
        self.status_l.setGeometry(QtCore.QRect(10, 1, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_l.setFont(font)
        self.status_l.setAlignment(QtCore.Qt.AlignCenter)
        self.status_l.setObjectName("status_l")
        self.line = QtWidgets.QFrame(self.status)
        self.line.setGeometry(QtCore.QRect(580, 0, 20, 41))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.status)
        self.line_2.setGeometry(QtCore.QRect(500, 0, 20, 41))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.status)
        self.line_3.setGeometry(QtCore.QRect(360, 0, 20, 41))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.status)
        self.line_4.setGeometry(QtCore.QRect(180, 0, 20, 41))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.tabWidget.addTab(self.Sensors, "")
        ######   Gear box tab                   ##########################
        self.Gearbox = QtWidgets.QWidget()
        self.Gearbox.setObjectName("Gearbox")
        
        ##### PLOT               ##############
        self.widget = QtWidgets.QWidget(self.Gearbox)
        self.widget.setGeometry(QtCore.QRect(200, 10, 700, 450))
        self.widget.setObjectName("widget")
        self.figure = plt.figure()
  
        # this is the Canvas Widget that
        # displays the 'figure'it takes the
        # 'figure' instance as a parameter to __init__
        self.canvas = FigureCanvas(self.figure)
        
        # this is the Navigation widget
        # it takes the Canvas widget and a parent
        self.toolbar = NavigationToolbar(self.canvas, self.widget)
  
        # creating a Vertical Box layout
 # Just some button connected to 'plot' method
        self.button = QPushButton('Plot')
          
        # adding action to the button
        self.button.clicked.connect(self.plot)
        # refresh canvas
        self.plt = QVBoxLayout(self.widget)
        # self.plt.setGeometry(QtCore.QRect(200, 10, 600, 500))  
          
        # adding tool bar to the layout
        self.plt.addWidget(self.toolbar)
          
        # adding canvas to the layout
        self.plt.addWidget(self.canvas)
          
        # adding push button to the layout
        # self.plt.addWidget(self.button)
          
        ##### Gear Box List            ######################
        self.gear_list = QtWidgets.QListWidget(self.Gearbox)
        self.gear_list.setGeometry(QtCore.QRect(10, 10, 71, 280))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gear_list.setFont(font)
        self.gear_list.setObjectName("gear_list")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.gear_list.addItem(item)
        # self.gear_list.currentItemChanged.connect(self.index_changed)
        self.gear_list.currentTextChanged.connect(self.text_changed)
#########################################################################
        ###### Down Shift table ######################################################## 
        self.down_shift_table = QtWidgets.QTableWidget(self.Gearbox)
        self.down_shift_table.setGeometry(QtCore.QRect(550, 500, 311, 91))
        self.down_shift_table.setFrameShape(QtWidgets.QFrame.Box)
        self.down_shift_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.down_shift_table.setMidLineWidth(1)
        self.down_shift_table.setObjectName("down_shift_table")
        self.down_shift_table.setColumnCount(5)
        self.down_shift_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_shift_table.setItem(0, 0, item)
        self.down_shift_table.horizontalHeader().setCascadingSectionResizes(False)
        self.down_shift_table.horizontalHeader().setDefaultSectionSize(50)
        self.down_shift_table.itemChanged.connect(lambda item: self.table_change(item,1))
        ###### Up Shift table ########################################################
        self.up_shift_table = QtWidgets.QTableWidget(self.Gearbox)
        self.up_shift_table.setGeometry(QtCore.QRect(190, 500, 311, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_shift_table.sizePolicy().hasHeightForWidth())
        self.up_shift_table.setSizePolicy(sizePolicy)
        self.up_shift_table.setFrameShape(QtWidgets.QFrame.Box)
        self.up_shift_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.up_shift_table.setMidLineWidth(1)
        self.up_shift_table.setObjectName("up_shift_table")
        self.up_shift_table.setColumnCount(5)
        self.up_shift_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.up_shift_table.setItem(0, 0, item)
        self.up_shift_table.horizontalHeader().setCascadingSectionResizes(False)
        self.up_shift_table.horizontalHeader().setDefaultSectionSize(50)
        self.up_shift_table.horizontalHeader().setMinimumSectionSize(30)
        
        self.up_shift_table.itemChanged.connect(lambda item: self.table_change(item,0))

        ###########################################################
        
        self.label_3 = QtWidgets.QLabel(self.Gearbox)
        self.label_3.setGeometry(QtCore.QRect(320, 470, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Gearbox)
        self.label_4.setGeometry(QtCore.QRect(660, 470, 51, 20))
        self.label_4.setObjectName("label_4")
    
        ###################################################
        self.checkBox_1 = QtWidgets.QCheckBox(self.Gearbox)
        self.checkBox_1.setGeometry(QtCore.QRect(90, 30, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_1.sizePolicy().hasHeightForWidth())
        self.checkBox_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setTristate(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_1.stateChanged.connect(lambda: self.gear_io_box(self.checkBox_1.checkState(),1))
        self.checkBox_2 = QtWidgets.QCheckBox(self.Gearbox)
        self.checkBox_2.setGeometry(QtCore.QRect(90, 60, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setTristate(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.stateChanged.connect(lambda: self.gear_io_box(self.checkBox_2.checkState(),2))
        self.checkBox_3 = QtWidgets.QCheckBox(self.Gearbox)
        self.checkBox_3.setGeometry(QtCore.QRect(90, 90, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setTristate(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.stateChanged.connect(lambda: self.gear_io_box(self.checkBox_3.checkState(),3))
        self.checkBox_4 = QtWidgets.QCheckBox(self.Gearbox)
        self.checkBox_4.setGeometry(QtCore.QRect(90, 130, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setTristate(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_4.stateChanged.connect(lambda: self.gear_io_box(self.checkBox_4.checkState(),4))
        
        self.gear_ratio_v = QtWidgets.QDoubleSpinBox(self.Gearbox)
        self.gear_ratio_v.setGeometry(QtCore.QRect(95, 310, 51, 22))
        self.gear_ratio_v.setSingleStep(0.1)
        self.gear_ratio_v.setProperty("value", 1.0)
        self.gear_ratio_v.setObjectName("gear_ratio_v")
        self.gear_ratio_v.valueChanged.connect(self.gear_ratio_value)
        self.gear_ratio_l = QtWidgets.QLabel(self.Gearbox)
        self.gear_ratio_l.setGeometry(QtCore.QRect(10, 310, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gear_ratio_l.setFont(font)
        self.gear_ratio_l.setObjectName("gear_ratio_l")
        self.tabWidget.addTab(self.Gearbox, "")
        ###### Torque converter clutchCC TAB ##########################################################
        self.TCC = QtWidgets.QWidget()
        self.TCC.setObjectName("TCC")
        ##### PLOT               ##############
        self.widget_p3 = QtWidgets.QWidget(self.TCC)
        self.widget_p3.setGeometry(QtCore.QRect(50, 10, 700, 450))
        self.widget_p3.setObjectName("widget_p3")
        self.figure_p3 = plt.figure()
        # self.fig_p3 , self.ax_p3= self.figure_p3.subplots(subplot_kw=dict(projection='3d'))
  
        # this is the Canvas Widget that
        # displays the 'figure'it takes the
        # 'figure' instance as a parameter to __init__
        self.canvas_p3 = FigureCanvas(self.figure_p3)
        
        # this is the Navigation widget
        # it takes the Canvas widget and a parent
        self.toolbar_p3 = NavigationToolbar(self.canvas_p3, self.widget_p3)
  
        # creating a Vertical Box layout
 # Just some button connected to 'plot' method
        self.button_p3 = QPushButton('Plot_p3')
          
        # adding action to the button
        self.button_p3.clicked.connect(self.plot3)
        # refresh canvas
        self.plt_p3 = QVBoxLayout(self.widget_p3)
        # self.plt.setGeometry(QtCore.QRect(200, 10, 600, 500))  
          
        # adding tool bar to the layout
        self.plt_p3.addWidget(self.button_p3)
        self.plt_p3.addWidget(self.toolbar_p3)  
        # adding canvas to the layout
        self.plt_p3.addWidget(self.canvas_p3)
        self.tabWidget.addTab(self.TCC, "")

        self.frame = QtWidgets.QFrame(self.TCC)
        self.frame.setGeometry(QtCore.QRect(80, 500, 571, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(340, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(230, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.TPF = QtWidgets.QDoubleSpinBox(self.frame)
        self.TPF.setGeometry(QtCore.QRect(340, 60, 61, 25))
        self.TPF.setDecimals(3)
        self.TPF.setObjectName("TPF")
        self.TPF.valueChanged.connect(self.plot3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 50, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.FTF = QtWidgets.QDoubleSpinBox(self.frame)
        self.FTF.setGeometry(QtCore.QRect(170, 60, 61, 25))
        self.FTF.setDecimals(3)
        self.FTF.setObjectName("FTF")
        self.FTF.valueChanged.connect(self.plot3)
        self.ESF = QtWidgets.QDoubleSpinBox(self.frame)
        self.ESF.setGeometry(QtCore.QRect(490, 60, 61, 25))
        self.ESF.setDecimals(3)
        self.ESF.setObjectName("ESF")
        self.ESF.valueChanged.connect(self.plot3)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(490, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(400, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.fluid_base_tmp = QtWidgets.QLCDNumber(self.frame)
        self.fluid_base_tmp.setGeometry(QtCore.QRect(110, 60, 41, 25))
        self.fluid_base_tmp.setDigitCount(3)
        self.fluid_base_tmp.setProperty("value", 100.0)
        self.fluid_base_tmp.setObjectName("fluid_base_tmp")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(150, 60, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(100, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(240, 10, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.TP = QtWidgets.QLCDNumber(self.frame)
        self.TP.setGeometry(QtCore.QRect(260, 60, 41, 25))
        self.TP.setDigitCount(3)
        self.TP.setProperty("value", 100.0)
        self.TP.setObjectName("TP")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(310, 60, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(470, 60, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.ES = QtWidgets.QLCDNumber(self.frame)
        self.ES.setGeometry(QtCore.QRect(420, 60, 41, 25))
        self.ES.setDigitCount(3)
        self.ES.setProperty("value", 100.0)
        self.ES.setObjectName("ES")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(400, 10, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")

        ##### Pressure control selonoid tab #########################
        self.PCS = QtWidgets.QWidget()
        self.PCS.setObjectName("PCS")
        self.tabWidget.addTab(self.PCS, "")
        self.CAN = QtWidgets.QWidget()
        self.CAN.setObjectName("CAN")
        self.tabWidget.addTab(self.CAN, "")
        TCU.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TCU)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuConnect = QtWidgets.QMenu(self.menuMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/HP/Documents/icons/icons/plug-connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuConnect.setIcon(icon)
        self.menuConnect.setObjectName("menuConnect")
        TCU.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TCU)
        self.statusbar.setObjectName("statusbar")
        TCU.setStatusBar(self.statusbar)
        self.actionCOM1 = QtWidgets.QAction(TCU)
        self.actionCOM1.setObjectName("actionCOM1")
        self.actionCOM2 = QtWidgets.QAction(TCU)
        self.actionCOM2.setObjectName("actionCOM2")
        self.actionProgram = QtWidgets.QAction(TCU)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/HP/Documents/icons/icons/system-monitor--arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProgram.setIcon(icon1)
        self.actionProgram.setObjectName("actionProgram")
        self.actionLoad = QtWidgets.QAction(TCU)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/HP/Documents/icons/icons/arrow-skip-090.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon2)
        self.actionLoad.setObjectName("actionLoad")
        self.actionReset_to_Defualt = QtWidgets.QAction(TCU)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/HP/Documents/icons/icons/arrow-circle-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset_to_Defualt.setIcon(icon3)
        self.actionReset_to_Defualt.setObjectName("actionReset_to_Defualt")
        self.actionSave_config = QtWidgets.QAction(TCU)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/HP/Documents/icons/icons/disk-return-black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_config.setIcon(icon4)
        self.actionSave_config.setObjectName("actionSave_config")
        self.actionload_Config_from_file = QtWidgets.QAction(TCU)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/HP/Documents/icons/icons/folder-horizontal-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionload_Config_from_file.setIcon(icon5)
        self.actionload_Config_from_file.setObjectName("actionload_Config_from_file")
        self.menuConnect.addAction(self.actionCOM1)
        self.menuConnect.addAction(self.actionCOM2)
        self.menuMenu.addAction(self.menuConnect.menuAction())
        self.menuMenu.addAction(self.actionProgram)
        self.menuMenu.addAction(self.actionLoad)
        self.menuMenu.addAction(self.actionReset_to_Defualt)
        self.menuMenu.addAction(self.actionSave_config)
        self.menuMenu.addAction(self.actionload_Config_from_file)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(TCU)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TCU)

    def retranslateUi(self, TCU):
        _translate = QtCore.QCoreApplication.translate
        TCU.setWindowTitle(_translate("TCU", "Transmission control unit"))
        self.tcu_tmp_l.setText(_translate("TCU", "TCU TEMP:"))
        self.tcu_volt_l.setText(_translate("TCU", "TCU Volage:"))
        self.tcu_ampl.setText(_translate("TCU", "TCU Current:"))
        self.label_6.setText(_translate("TCU", "TCU :"))
        self.o2amp_l.setText(_translate("TCU", "OUT 2 Amp:"))
        self.o1amp_l.setText(_translate("TCU", "OUT 1 Amp:"))
        self.o3amp_l.setText(_translate("TCU", "OUT 3 Amp:"))
        self.o4amp_l.setText(_translate("TCU", "OUT 4 Amp:"))
        self.o5amp_l.setText(_translate("TCU", "OUT 5 Amp:"))
        self.o6amp_l.setText(_translate("TCU", "OUT 6 Amp:"))
        self.o7amp_l.setText(_translate("TCU", "OUT 7 Amp:"))
        self.o8amp_l.setText(_translate("TCU", "OUT 8 Amp:"))
        self.health_L.setText(_translate("TCU", "TCU health ckeck"))
        self.dmod_l.setText(_translate("TCU", "Drive Mod:"))
        self.dmod_v.setText(_translate("TCU", "Sport"))
        self.gear_v.setText(_translate("TCU", "P"))
        self.gear_l.setText(_translate("TCU", "Gear:"))
        self.brake_l.setText(_translate("TCU", "Brake"))
        self.ing_l.setText(_translate("TCU", "Ignition"))
        self.status_v.setText(_translate("TCU", "Not Connected"))
        self.status_l.setText(_translate("TCU", "Status:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sensors), _translate("TCU", "Sensors"))
        self.label_5.setText(_translate("TCU", "TPF"))
        self.label_2.setText(_translate("TCU", "<html><head/><body><p align=\"center\">FTF</p></body></html>"))
        self.label_7.setText(_translate("TCU", "+"))
        self.label.setText(_translate("TCU", "TCC PWM :"))
        self.label_8.setText(_translate("TCU", "ESF"))
        self.label_9.setText(_translate("TCU", "+"))
        self.label_11.setText(_translate("TCU", "*"))
        self.label_12.setText(_translate("TCU", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">(Fluid - Base) </span></p><p align=\"center\"><span style=\" font-size:8pt;\">Temp</span></p></body></html>"))
        self.label_13.setText(_translate("TCU", "<html><head/><body><p align=\"center\"><a name=\"Throttle_position_sensor_(TPS)\"/><span style=\" font-size:8pt;\">T</span><span style=\" font-size:8pt;\">hrottle position</span></p></body></html>"))
        self.label_14.setText(_translate("TCU", "*"))
        self.label_15.setText(_translate("TCU", "*"))
        self.label_16.setText(_translate("TCU", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Engine Speed</span></p></body></html>"))
        
        __sortingEnabled = self.gear_list.isSortingEnabled()
        self.gear_list.setSortingEnabled(False)
        item = self.gear_list.item(0)
        item.setText(_translate("TCU", "Park"))
        item = self.gear_list.item(1)
        item.setText(_translate("TCU", "Reverse"))
        item = self.gear_list.item(2)
        item.setText(_translate("TCU", "Neutral"))
        item = self.gear_list.item(3)
        item.setText(_translate("TCU", "Gear 1"))
        item = self.gear_list.item(4)
        item.setText(_translate("TCU", "Gear 2"))
        item = self.gear_list.item(5)
        item.setText(_translate("TCU", "Gear 3"))
        item = self.gear_list.item(6)
        item.setText(_translate("TCU", "Gear 4"))
        item = self.gear_list.item(7)
        item.setText(_translate("TCU", "Gear 5"))
        item = self.gear_list.item(8)
        item.setText(_translate("TCU", "Gear 6"))
        item = self.gear_list.item(9)
        item.setText(_translate("TCU", "Gear 7"))
        item = self.gear_list.item(10)
        item.setText(_translate("TCU", "Gear 8"))
        item = self.gear_list.item(11)
        item.setText(_translate("TCU", "Gear 9"))
        self.gear_list.setSortingEnabled(__sortingEnabled)
        item = self.down_shift_table.verticalHeaderItem(0)
        item.setText(_translate("TCU", "Speed"))
        item = self.down_shift_table.verticalHeaderItem(1)
        item.setText(_translate("TCU", "Throttle"))
        item = self.down_shift_table.horizontalHeaderItem(0)
        item.setText(_translate("TCU", "1"))
        item = self.down_shift_table.horizontalHeaderItem(1)
        item.setText(_translate("TCU", "2"))
        item = self.down_shift_table.horizontalHeaderItem(2)
        item.setText(_translate("TCU", "3"))
        item = self.down_shift_table.horizontalHeaderItem(3)
        item.setText(_translate("TCU", "4"))
        item = self.down_shift_table.horizontalHeaderItem(4)
        item.setText(_translate("TCU", "5"))
        __sortingEnabled = self.down_shift_table.isSortingEnabled()
        self.down_shift_table.setSortingEnabled(False)
        self.down_shift_table.setSortingEnabled(__sortingEnabled)
        item = self.up_shift_table.verticalHeaderItem(0)
        item.setText(_translate("TCU", "Speed"))
        item = self.up_shift_table.verticalHeaderItem(1)
        item.setText(_translate("TCU", "Throttle"))
        item = self.up_shift_table.horizontalHeaderItem(0)
        item.setText(_translate("TCU", "1"))
        item = self.up_shift_table.horizontalHeaderItem(1)
        item.setText(_translate("TCU", "2"))
        item = self.up_shift_table.horizontalHeaderItem(2)
        item.setText(_translate("TCU", "3"))
        item = self.up_shift_table.horizontalHeaderItem(3)
        item.setText(_translate("TCU", "4"))
        item = self.up_shift_table.horizontalHeaderItem(4)
        item.setText(_translate("TCU", "5"))
        __sortingEnabled = self.up_shift_table.isSortingEnabled()
        self.up_shift_table.setSortingEnabled(False)
        self.up_shift_table.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("TCU", "Up Shift"))
        self.label_4.setText(_translate("TCU", "Down Shift"))
        self.checkBox_1.setText(_translate("TCU", "Out 1"))
        self.checkBox_2.setText(_translate("TCU", "Out 2"))
        self.checkBox_3.setText(_translate("TCU", "Out 3"))
        self.checkBox_4.setText(_translate("TCU", "Out 4"))
        self.gear_ratio_l.setText(_translate("TCU", "Gear Ratio:"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gearbox), _translate("TCU", "Shift solenoids"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TCC), _translate("TCU", "Torque converter clutch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PCS), _translate("TCU", "Pressure control solenoids"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CAN), _translate("TCU", "CAN"))

        self.menuMenu.setTitle(_translate("TCU", "Menu"))
        self.menuConnect.setTitle(_translate("TCU", "Connect"))
        self.actionCOM1.setText(_translate("TCU", "COM1"))
        self.actionCOM2.setText(_translate("TCU", "COM2"))
        self.actionProgram.setText(_translate("TCU", "Program"))
        self.actionLoad.setText(_translate("TCU", "Load from TCU"))
        self.actionReset_to_Defualt.setText(_translate("TCU", "Reset to defualt"))
        self.actionSave_config.setText(_translate("TCU", "Save config"))
        self.actionload_Config_from_file.setText(_translate("TCU", "load Config from file"))

    # def index_changed(self, i): # Not an index, i is a QListWidgetItem
    #     print(i.text())

    def text_changed(self, s): # s is a str
        global gear_list
        # global G1 , G2 , G3 , G4 , G5 , G6 , G7 , G8 , G9
        global P , R , N
        global G1 , G2 , G3 , G4 , G5 , G6 , G7 , G8 , G9

        global show
        gear_list=s
        show = 1 
        # print(s)
        print("show list:",show,gear_list)
        self.down_shift_table.clearContents()
        self.up_shift_table.clearContents()
        self.figure.clear()
        self.canvas.draw()
        if gear_list=="Park" :
            self.checkBox_1.setCheckState(P.O1)
            self.checkBox_2.setCheckState(P.O2)
            self.checkBox_3.setCheckState(P.O3)
            self.checkBox_4.setCheckState(P.O4)
            self.checkBox_4.setCheckState(P.O5)
            self.gear_ratio_v.setValue(P.ratio)
        if gear_list=="Reverse" :
            self.checkBox_1.setCheckState(R.O1)
            self.checkBox_2.setCheckState(R.O2)
            self.checkBox_3.setCheckState(R.O3)
            self.checkBox_4.setCheckState(R.O4)
            self.checkBox_4.setCheckState(R.O5)
            self.gear_ratio_v.setValue(R.ratio)
        if gear_list=="Neutral" :
            
            self.checkBox_1.setCheckState(N.O1)
            self.checkBox_2.setCheckState(N.O2)
            self.checkBox_3.setCheckState(N.O3)
            self.checkBox_4.setCheckState(N.O4)
            self.checkBox_4.setCheckState(N.O5)
            self.gear_ratio_v.setValue(N.ratio)
        if gear_list=="Gear 1" :
            self.plot(G1.data_x,G1.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G1.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G1.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G1.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G1.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
                print(i,str(G1.data_x[i]),str(G1.data_y[i][0]))
            self.checkBox_1.setCheckState(G1.O1)
            self.checkBox_2.setCheckState(G1.O2)
            self.checkBox_3.setCheckState(G1.O3)
            self.checkBox_4.setCheckState(G1.O4)
            self.checkBox_4.setCheckState(G1.O5)
            self.gear_ratio_v.setValue(G1.ratio)
        if gear_list=="Gear 2" :
            self.plot(G2.data_x,G2.data_y)
            for i in range (0,5):  
                print(i,str(G2.data_x[i]),str(G2.data_y[i][0]))   
                item = QtWidgets.QTableWidgetItem(str(G2.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G2.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G2.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G2.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
                
            self.checkBox_1.setCheckState(G2.O1)
            self.checkBox_2.setCheckState(G2.O2)
            self.checkBox_3.setCheckState(G2.O3)
            self.checkBox_4.setCheckState(G2.O4)
            self.checkBox_4.setCheckState(G2.O5)
            self.gear_ratio_v.setValue(G2.ratio)
        if gear_list=="Gear 3" :
            self.plot(G3.data_x,G3.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G3.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G3.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G3.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G3.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
                print(i,str(G3.data_x[i]),str(G3.data_y[i][0]))
            self.checkBox_1.setCheckState(G3.O1)
            self.checkBox_2.setCheckState(G3.O2)
            self.checkBox_3.setCheckState(G3.O3)
            self.checkBox_4.setCheckState(G3.O4)
            self.checkBox_4.setCheckState(G3.O5)
            self.gear_ratio_v.setValue(G3.ratio)
        if gear_list=="Gear 4" :
            self.plot(G4.data_x,G4.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G4.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G4.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G4.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G4.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
            self.checkBox_1.setCheckState(G4.O1)
            self.checkBox_2.setCheckState(G4.O2)
            self.checkBox_3.setCheckState(G4.O3)
            self.checkBox_4.setCheckState(G4.O4)
            self.checkBox_4.setCheckState(G4.O5)
            self.gear_ratio_v.setValue(G4.ratio)
        if gear_list=="Gear 5" :
            self.plot(G5.data_x,G5.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G5.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G5.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G5.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G5.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
            self.checkBox_1.setCheckState(G5.O1)
            self.checkBox_2.setCheckState(G5.O2)
            self.checkBox_3.setCheckState(G5.O3)
            self.checkBox_4.setCheckState(G5.O4)
            self.checkBox_4.setCheckState(G5.O5)
            self.gear_ratio_v.setValue(G5.ratio)
        if gear_list=="Gear 6" :
            self.plot(G6.data_x,G6.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G6.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G6.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G6.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G6.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
            self.checkBox_1.setCheckState(G6.O1)
            self.checkBox_2.setCheckState(G6.O2)
            self.checkBox_3.setCheckState(G6.O3)
            self.checkBox_4.setCheckState(G6.O4)
            self.checkBox_4.setCheckState(G6.O5)
            self.gear_ratio_v.setValue(G6.ratio)
        if gear_list=="Gear 7" :
            self.plot(G7.data_x,G7.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G7.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G7.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G7.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G7.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
            self.checkBox_1.setCheckState(G7.O1)
            self.checkBox_2.setCheckState(G7.O2)
            self.checkBox_3.setCheckState(G7.O3)
            self.checkBox_4.setCheckState(G7.O4)
            self.checkBox_4.setCheckState(G7.O5)
            self.gear_ratio_v.setValue(G7.ratio)
        if gear_list=="Gear 8" :
            self.plot(G8.data_x,G8.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G8.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G8.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G8.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G8.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
            self.checkBox_1.setCheckState(G8.O1)
            self.checkBox_2.setCheckState(G8.O2)
            self.checkBox_3.setCheckState(G8.O3)
            self.checkBox_4.setCheckState(G8.O4)
            self.checkBox_4.setCheckState(G8.O5)
            self.gear_ratio_v.setValue(G8.ratio)
        if gear_list=="Gear 9" :
            self.plot(G9.data_x,G9.data_y)
            for i in range (0,5):     
                item = QtWidgets.QTableWidgetItem(str(G9.data_x[i]))
                self.up_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G9.data_x[i]))
                self.down_shift_table.setItem(0,i,item)
                item = QtWidgets.QTableWidgetItem(str(G9.data_y[i][0]))
                self.up_shift_table.setItem(1,i,item)
                item = QtWidgets.QTableWidgetItem(str(G9.data_y[i][1]))
                self.down_shift_table.setItem(1,i,item)
            self.checkBox_1.setCheckState(G9.O1)
            self.checkBox_2.setCheckState(G9.O2)
            self.checkBox_3.setCheckState(G9.O3)
            self.checkBox_4.setCheckState(G9.O4)
            self.checkBox_4.setCheckState(G9.O5)
            self.gear_ratio_v.setValue(G9.ratio)
        show = 0
        
    #### check box state change #############################
    def gear_io_box(self,sig,num):
        global gear_list
        global G1 , G2 , G3 , G4 , G5 , G6 , G7 , G8 , G9
        global P , R , N
        if gear_list=="Park" :
            
            if num == 1 :
                P.O1=sig
            if num == 2 :
                P.O2=sig
            if num == 3 :
                P.O3=sig
            if num == 4 :
                P.O4=sig
            print(P)
        if gear_list=="Reverse" :
            
            if num == 1 :
                R.O1=sig
            if num == 2 :
                R.O2=sig
            if num == 3 :
                R.O3=sig
            if num == 4 :
                R.O4=sig
            print(R)
        if gear_list=="Neutral" :
            
            if num == 1 :
                N.O1=sig
            if num == 2 :
                N.O2=sig
            if num == 3 :
                N.O3=sig
            if num == 4 :
                N.O4=sig
            print(N)
        if gear_list=="Gear 1" :
            
            if num == 1 :
                G1.O1=sig
            if num == 2 :
                G1.O2=sig
            if num == 3 :
                G1.O3=sig
            if num == 4 :
                G1.O4=sig
        if gear_list=="Gear 2" :
            
            if num == 1 :
                G2.O1=sig
            if num == 2 :
                G2.O2=sig
            if num == 3 :
                G2.O3=sig
            if num == 4 :
                G2.O4=sig
        if gear_list=="Gear 3" :
            
            if num == 1 :
                G3.O1=sig
            if num == 2 :
                G3.O2=sig
            if num == 3 :
                G3.O3=sig
            if num == 4 :
                G3.O4=sig
        if gear_list=="Gear 4" :
            
            if num == 1 :
                G4.O1=sig
            if num == 2 :
                G4.O2=sig
            if num == 3 :
                G4.O3=sig
            if num == 4 :
                G4.O4=sig
        if gear_list=="Gear 5" :
            if num == 1 :
                G5.O1=sig
            if num == 2 :
                G5.O2=sig
            if num == 3 :
                G5.O3=sig
            if num == 4 :
                G5.O4=sig
        if gear_list=="Gear 6" :
            
            if num == 1 :
                G6.O1=sig
            if num == 2 :
                G6.O2=sig
            if num == 3 :
                G6.O3=sig
            if num == 4 :
                G6.O4=sig
        if gear_list=="Gear 7" :
            
            if num == 1 :
                G7.O1=sig
            if num == 2 :
                G7.O2=sig
            if num == 3 :
                G7.O3=sig
            if num == 4 :
                G7.O4=sig
        if gear_list=="Gear 8" :
            
            if num == 1 :
                G8.O1=sig
            if num == 2 :
                G8.O2=sig
            if num == 3 :
                G8.O3=sig
            if num == 4 :
                G8.O4=sig
        if gear_list=="Gear 9" :
            
            if num == 1 :
                G9.O1=sig
            if num == 2 :
                G9.O2=sig
            if num == 3 :
                G9.O3=sig
            if num == 4 :
                G9.O4=sig
        
        print(gear_list)
        # print(s)


    def gear_ratio_value(self):
        global gear_list
        global G1 , G2 , G3 , G4 , G5 , G6 , G7 , G8 , G9
        global P , R , N
        ratio_value = self.gear_ratio_v.value()
        
        if gear_list=="Reverse" :
            
            R.ratio=ratio_value
            print(R)
        if gear_list=="Gear 1" :
            
            G1.ratio=ratio_value
            print(G1)
        if gear_list=="Gear 2" :
            
            G2.ratio=ratio_value
            print(G2)
        if gear_list=="Gear 3" :
            
            G3.ratio=ratio_value
            print(G3)
        if gear_list=="Gear 4" :
            
            G4.ratio=ratio_value
            print(G4)
        if gear_list=="Gear 5" :
            G5.ratio=ratio_value
        if gear_list=="Gear 6" :
            
            G6.ratio=ratio_value
        if gear_list=="Gear 7" :
            
            G7.ratio=ratio_value
        if gear_list=="Gear 8" :
            
            G8.ratio=ratio_value
        if gear_list=="Gear 9" :
            
            G9.ratio=ratio_value
    def plot(self,data_x ,data_y):
        global Speed
        global TPS_V 
        # clearing old figure
        self.figure.clear()

        # create an axis
        ax = self.figure.add_subplot(111)
        ax.grid()
        ax.set_xlabel("TPS (%)")
        ax.set_ylabel("Speed (KM/H)")
        # plot data
        ax.plot(data_x,data_y, '*-',TPS_V,Speed,"r+", markersize=10)

        # refresh canvas
        self.canvas.draw()

    def plot3(self ):
        ftf = self.FTF.value()
        tpf = self.TPF.value()
        esf = self.TPF.value()
        def f(x, y):
            return (x *tpf + y * esf + ftf * 25)
        z = np.linspace(5, 100, 100)
        y = np.linspace(0, 10000, 100)
        x = np.linspace(0, 100, 100)

        X, Y = np.meshgrid(x, y)
        Z = f(X, Y)
        theta = np.linspace(0, 2*np.pi)

        # random data  ,data_x ,data_y,data_z
        data_x = X
        data_y = Y
        data_z = Z
        # tsstdata = [[1,2],[2,3],[5,6]]
        # clearing old figure
        self.figure_p3.clear()

        # create an axis
        # self.figure_p3, ax = plt.subplots(subplot_kw=dict(projection='3d'))
        ax = self.figure_p3.add_subplot(1, 1, 1, projection='3d')
        ax.plot_surface(X, Y, Z, rstride=1, cstride=1,cmap='viridis', edgecolor='none')
        # plot data

        # refresh canvas
        self.canvas_p3.draw()
    def table_change(self, item,tbl):
        global gear_list , show
        global G1,G2,G3,G4,G5,G6,G7,G8,G9
        row = item.row()
        col = item.column()
        data = int(item.text())
        if show == 0:
            print("table change data row col table list",data,row,col,tbl,gear_list)
            if gear_list == "Gear 1":
                if row == 0 :
                    G1.data_x[col]=data
                if row == 1:
                    G1.data_y[col][tbl]=data
                self.plot(G1.data_x,G1.data_y)
                print(11111111)
            if gear_list == "Gear 2":
                if row == 0 :
                    G2.data_x[col]=data
                if row == 1:
                    G2.data_y[col][tbl]=data
                self.plot(G2.data_x,G2.data_y)
                print(2222222222)
            if gear_list == "Gear 3":
                if row == 0 :
                    G3.data_x[col]=data
                if row == 1:
                    G3.data_y[col][tbl]=int(data)
                self.plot(G3.data_x,G3.data_y)
            if gear_list == "Gear 4":
                if row == 0 :
                    G4.data_x[col]=data
                if row == 1:
                    G4.data_y[col][tbl]=data
                self.plot(G4.data_x,G4.data_y)
            if gear_list == "Gear 5":
                if row == 0 :
                    G5.data_x[col]=data
                if row == 1:
                    G5.data_y[col][tbl]=data
                self.plot(G5.data_x,G5.data_y)
            if gear_list == "Gear 6":
                if row == 0 :
                    G6.data_x[col]=data
                if row == 1:
                    G6.data_y[col][tbl]=data
                self.plot(G6.data_x,G6.data_y)
            if gear_list == "Gear 7":
                if row == 0 :
                    G7.data_x[col]=data
                if row == 1:
                    G7.data_y[col][tbl]=data
                self.plot(G7.data_x,G7.data_y)
            if gear_list == "Gear 8":
                if row == 0 :
                    G8.data_x[col]=data
                if row == 1:
                    G8.data_y[col][tbl]=data
                self.plot(G8.data_x,G8.data_y)
            if gear_list == "Gear 9":
                if row == 0 :
                    G9.data_x[col]=int(data)
                if row == 1:
                    G9.data_y[col][tbl]=int(data)
                self.plot(G9.data_x,G9.data_y)
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")  #['Breeze', 'Oxygen', 'QtCurve', 'Windows', 'Fusion']
    palette = QPalette()
    palette.setColor(QPalette.Window, QColor(53, 53, 53))
    palette.setColor(QPalette.WindowText, Qt.white)
    palette.setColor(QPalette.Base, QColor(25, 25, 25))
    palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    palette.setColor(QPalette.ToolTipBase, Qt.black)
    palette.setColor(QPalette.ToolTipText, Qt.white)
    palette.setColor(QPalette.Text, Qt.white)
    palette.setColor(QPalette.Button, QColor(53, 53, 53))
    palette.setColor(QPalette.ButtonText, Qt.white)
    palette.setColor(QPalette.BrightText, Qt.red)
    palette.setColor(QPalette.Link, QColor(42, 130, 218))
    palette.setColor(QPalette.Highlight, QColor(42, 130, 218))
    palette.setColor(QPalette.HighlightedText, Qt.black)
    app.setPalette(palette)
    TCU = QtWidgets.QMainWindow()
    ui = Ui_TCU()
    ui.setupUi(TCU)
    TCU.show()
    sys.exit(app.exec_())
